# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b7e4f9694761cad7813a0a0a343aa5b5a6d1b8231d27b53571f52d25b3ea2bc28b07fd0bcf348a71e6b156752c9b6500dc6fc47d965fdb48d8a13eb62219f78

test:
  secret_key_base: 870798f6d85476de33075f1926ed43c8752672c9ba99a8d6d6de9a510a21f4c610659972519ee1234e246f7d4f3b690291b00f983f6470693c849c35cacb62eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
